version: "3.9"

services:
  chrome:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.chrome
    image: booker-chrome
    ports:
      - 4444:4444

  app:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.app
    image: booker-app
    ports:
      - 80:80
