name: Reserve

on:
  schedule:
    - cron: '0 1 * * 3'

jobs:
  reserve:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    container:
      image: python:3.10-slim
      env:
        SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
        RESERVATION_URL: ${{ secrets.RESERVATION_URL }}
        DATE_PATTERN: ${{ secrets.DATE_PATTERN }}
        NAME_KANJI: ${{ secrets.NAME_KANJI }}
        NAME_KANA: ${{ secrets.NAME_KANA }}
        TELEPHONE: ${{ secrets.TELEPHONE }}
        EMAIL: ${{ secrets.EMAIL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        LANG: ja_JP.UTF-8
        LANGUAGE: ja_JP:ja
        LC_ALL: ja_JP.UTF-8
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/chrome

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup locales
        run: |
          apt update && apt install -y locales
          sed -i '/ja_JP.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

      - name: Install packages
        run: |
          pip install .

      - name: Reserve
        run: |
          booker
